### ISSUE TITLE
Mobile phone number should be pointing at same user in Argentina

### ISSUE THREAD

**Issue by santiagosemhan** [Jibber-Inc/Jibber-iOS#2]
In Argentina, If you fill on input +549376433XX02 or 376433XX02 (with AR flag) both numbers correspond to the same user.
Currently, both are treated as different users.

Useful documentation: https://en.wikipedia.org/wiki/List_of_mobile_telephone_prefixes_by_country

**Comment by Benjamindodgson** [comment]
@santiagosemhan This would need to be adjusted on the backend as the client doesn't do the user lookup.

**Comment by santiagosemhan** [comment]
I thought that you were using a library to parse entered phone number. So, we can look at the user phone number in the backend side but would be useful to send full number on all countries

**Comment by Benjamindodgson** [comment]
Oh I see so you want the full number. Currently its being formatted to e164.

**Comment by santiagosemhan** [comment]
Close. It is mentioned in https://github.com/Ours-Inc/benji-backend/issues/174. It will be solved on BE.
